---

- name: add key repo hhvm
  apt_key: keyserver=keyserver.ubuntu.com id=5a16e7281be7a449
  sudo: yes

- name: add hhvm to repo
  apt_repository: repo='deb http://dl.hhvm.com/ubuntu trusty main' state=present
  sudo: yes
  register: repo

- name: apt update
  apt: update_cache=yes
  sudo: yes
  when: repo.changed

- name: install hhvm
  apt: name={{ item  }} state=latest
  with_items:
    - hhvm
    - hhvm-dev
  sudo: yes
