---

- name: install dependency package for upgrade ansible
  apt: name={{ item }} state=present
  with_items:
    - python-pycurl
    - software-properties-common
  sudo: yes

- name: add ansible to repository
  apt_repository: repo='ppa:ansible/ansible'
  sudo: yes
  register: repo

- name: apt update
  apt: update_cache=yes
  sudo: yes
  when: repo.changed

- name: reinstall ansible
  apt: name=ansible state=latest
  sudo: yes
